// <auto-generated />
using System;
using FIAP.Agroplus.Sprint3.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FIAP.Agroplus.Sprint3.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240912224935_DbCreate")]
    partial class DbCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIAP.Agroplus.Sprint3.Domain.Entities.PlantacaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CnpjProdutor")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CNPJ_PRODUTO");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("NomeProdutor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME_PRODUTO");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("TamanhoEmHectares")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TAMANHO_EM_HECTARES");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.ToTable("T_PLANTACAO");
                });

            modelBuilder.Entity("FIAP.Agroplus.Sprint3.Domain.Entities.RegiaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("PlantioMaisFrequente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PLANTIO_FREQUENTE");

                    b.Property<decimal>("PrecipitacaoMedia")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PRECIPITACAO_MEDIA");

                    b.Property<string>("RegiaoBR")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REGIAO_BRASIL");

                    b.Property<decimal>("TemperaturaMedia")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TEMPERATURA_MEDIA");

                    b.HasKey("Id");

                    b.ToTable("T_REGIAO");
                });

            modelBuilder.Entity("FIAP.Agroplus.Sprint3.Domain.Entities.PlantacaoEntity", b =>
                {
                    b.HasOne("FIAP.Agroplus.Sprint3.Domain.Entities.RegiaoEntity", "Regiao")
                        .WithMany()
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });
#pragma warning restore 612, 618
        }
    }
}
